# Generated by Django 3.2.5 on 2022-05-04 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Identite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('tel', models.IntegerField()),
                ('detail', models.CharField(default=' ', max_length=1000)),
                ('image1', models.ImageField(default=None, upload_to='images')),
                ('image2', models.ImageField(default=None, upload_to='images')),
                ('image3', models.ImageField(default=None, upload_to='images')),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image')),
            ],
        ),
    ]
